---
title: "Mapping"
author: "Mira Tang"
date: "11/4/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
pacman::p_load("leaflet","sp","magrittr","maps","htmltools","rgdal","ggplot2","maptools","XML","readr","rgeos","rmapshaper","tidyverse","lubridate","ggmap",update = FALSE)
```

```{r}
# Import data
mayorsfoodcourt <- read_csv("mayorsfoodcourt.csv")

# Data cleaning
mayorsfoodcourt$VioYear <- lubridate::year(mayorsfoodcourt$VIOLDTTM)
mayorsfoodcourt %>% filter(LICSTATUS == "Active") %>% select(businessName,LICSTATUS,ViolLevel,VIOLDTTM,Address,CITY,ZIP,Location) %>% separate(Location, c("lat","lng"),",")-> foodcourt
foodcourt$lat <- as.numeric(gsub("\\(", "", foodcourt$lat))
foodcourt$lng <- as.numeric(gsub(")", "", foodcourt$lng))

# How many NAs in violation date
sum(is.na(foodcourt$VIOLDTTM))

# Count the violation times
foodcourt %>% group_by(businessName,Address) %>% count() %>% arrange(desc(n))  -> food
colnames(food)[3] <- "VioCount"

# Separate the longitude and latitude
foodcourt %>% select(businessName,LICSTATUS,Address,CITY,ZIP,lat,lng) -> location
location <- unique(location)

# How many NAs in location
sum(is.na(location$lat))
as.numeric(sum(is.na(location$lat))/count(unique(location)))

# Create a dataset with count of violation times and the geographic info of foodcourts
food$ID <- paste(food$businessName,food$Address)
location$ID <- paste(location$businessName,location$Address)
food <- left_join(food,location,by =  "ID")
food$businessName.y <- NULL
food$Address.y <- NULL
food$ID <- NULL
food$LICSTATUS <- NULL
colnames(food)[1] <- "businessName"
colnames(food)[2] <- "Address"
food <- na.omit(food)
```

```{r}
# Top 50
content <- paste(sep = "<br/>",
                 food$businessName,
                 food$Address,
                 food$CITY,
                 food$ZIP
)

rIcon <- makeIcon(
  iconUrl = "https://image.flaticon.com/icons/svg/138/138310.svg",
  iconWidth = 15, iconHeight = 15,
  iconAnchorX = 22, iconAnchorY = 94,
  shadowUrl = "https://image.flaticon.com/icons/svg/138/138310.svg",
  shadowWidth = 15, shadowHeight = 15,
  shadowAnchorX = 4, shadowAnchorY = 62
)

leaflet(data = food[1:50,]) %>%
  addTiles() %>%
  addMarkers(~lng, ~lat, icon = rIcon, popup = ~content,
             options = popupOptions(closeButton = TRUE))
# %>% addProviderTiles(providers$Stamen.Toner)
# %>% addProviderTiles(providers$CartoDB.Positron)
# %>% addProviderTiles(providers$Esri.NatGeoWorldMap)
```

```{r, warning = FALSE}
boston_map <- make_bbox(lat = lat, lon = lng, data = food[1:50,])
boston_map <- get_map(location = boston_map, source = "google", maptype = "hybrid")
ggmap(boston_map) + 
  geom_point(data = food[1:50,], mapping = aes(x = lng, y = lat, size= VioCount, color = "red")) +
  guides(color = FALSE)
```





